sudo: required
services:
    - docker

before_install:
    - docker build -f ./react-client/Dockerfile.dev ./react-client -t ahy94/react-client

script:
    - docker run -e CI=true ahy94/react-client npm test

after_success:
    - docker build -t ahy94/dockerizing-multiple-services-react-client ./react-client
    - docker build -t ahy94/dockerizing-multiple-services-express-server ./express
    - docker build -t ahy94/dockerizing-multiple-services-worker ./worker
    - docker build -t ahy94/dockerizing-multiple-services-nginx ./nginx
    - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
    - docker push ahy94/dockerizing-multiple-services-react-client
    - docker push ahy94/dockerizing-multiple-services-express-server
    - docker push ahy94/dockerizing-multiple-services-worker
    - docker push ahy94/dockerizing-multiple-services-nginx

deploy:
    #edge: true
    provider: elasticbeanstalk
    region: us-west-1
    app: multi-docker
    env: MultiDocker-env
    bucket_name: elasticbeanstalk-us-west-1-697748264580
    bucket_path: docker-multi-bucket-path
    on:
        branch: master
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
        